export const add = 'add'
export const remove = 'remove'
export const edit = 'edit'
export const complete = 'complete'
export const completeAll = 'completeAll'
export const clearCompleted = 'clearCompleted'
